name = "asreseocom"
account_id = "ac07c7450925ccb475ebfc9ab75103e1"
main = "worker.ts"
compatibility_date = "2025-12-18"
compatibility_flags = ["nodejs_compat"]

send_email = [
  { name = "asreseo" },
  { name = "EMAIL" }
]

[assets]
directory = "./dist"
binding = "ASSETS"