import path from 'node:path';
import { buildOgSvg, renderCardPair } from './generate-og-image.mjs';

const allCards = [
  // ==========================================
  // 1. CORE SITE PAGES
  // ==========================================
  {
    base: 'public/og/about-hero',
    title: 'Infrastructure Manifesto & Systems',
    eyebrow: '[ABOUT // ARCHITECTURE_OVERVIEW]',
    descLine1: 'Engineering data-backed digital dominance through deterministic systems,',
    descLine2: 'verifiable search telemetry, and zero black-box promises.',
    tag1: 'Deterministic SEO',
    tag1Sub: 'Mathematically proven crawl logic',
    tag2: 'Autonomous Nodes',
    tag2Sub: 'n8n & agentic workflows',
    tag3: 'Verifiable SLAs',
    tag3Sub: 'Full reporting transparency',
  },
  {
    base: 'public/og/contact-hero',
    title: 'Dispatch Terminal & Direct Comms',
    eyebrow: '[CONTACT // SECURE_DISPATCH]',
    descLine1: 'Direct technical consultation with senior SEO engineers & AI strategists.',
    descLine2: 'Cloudflare native encrypted dispatch with sub-24h turnaround.',
    tag1: 'Direct Line',
    tag1Sub: 'No junior account managers',
    tag2: 'Free Audit',
    tag2Sub: 'Comprehensive technical crawl',
    tag3: 'Zero Lock-In',
    tag3Sub: 'Transparent engagement models',
  },
  {
    base: 'public/og/faq-hero',
    title: 'SEO & Search Architecture FAQ',
    eyebrow: '[FAQ // KNOWLEDGE_BASE]',
    descLine1: 'Definitive technical and strategic answers on algorithmic SEO, AEO/GEO,',
    descLine2: 'Google Ads budget economics, Core Web Vitals, and agency SLAs.',
    tag1: 'SEO Timeline',
    tag1Sub: '2-3mo early, 6mo stable',
    tag2: 'White-Hat SLA',
    tag2Sub: 'Strict algorithm adherence',
    tag3: 'Pricing Models',
    tag3Sub: 'Transparent milestone contracts',
  },
  {
    base: 'public/og/consultation-hero',
    title: 'Executive Technical Consultation',
    eyebrow: '[CONSULTATION // AUDIT_DISPATCH]',
    descLine1: 'Zero-obligation architectural audit and search engine growth roadmap.',
    descLine2: 'Direct collaboration with principal SEO architects & AI engineers.',
    tag1: 'Full Audit',
    tag1Sub: 'Technical & crawl health check',
    tag2: 'Growth Matrix',
    tag2Sub: 'Competitor gap classification',
    tag3: '100% Free',
    tag3Sub: 'Before any contract commitment',
  },
  {
    base: 'public/og/support-hero',
    title: 'Support SLA & System Telemetry',
    eyebrow: '[SUPPORT // CLIENT_SLA]',
    descLine1: 'Continuous uptime telemetry, search console health monitoring,',
    descLine2: 'security vulnerability defense, and rapid deployment engineering.',
    tag1: 'Uptime SLA',
    tag1Sub: '99.99% edge availability',
    tag2: 'GSC Telemetry',
    tag2Sub: 'Continuous index monitoring',
    tag3: 'Fast Turnaround',
    tag3Sub: 'Dedicated senior engineers',
  },
  {
    base: 'public/og/legal-hero',
    title: 'Privacy Policy & Terms of Service',
    eyebrow: '[LEGAL // DATA_GOVERNANCE]',
    descLine1: 'Transparent data governance, privacy compliance, and service terms.',
    descLine2: 'Engineered for international compliance with zero unauthorized data sharing.',
    tag1: 'Data Privacy',
    tag1Sub: 'Zero unauthorized third-party sharing',
    tag2: 'GDPR / CCPA',
    tag2Sub: 'Privacy by design',
    tag3: 'Service Terms',
    tag3Sub: 'Transparent client rights',
  },

  // ==========================================
  // 2. SERVICES & CATEGORY HUBS
  // ==========================================
  {
    base: 'public/og/services-hero',
    title: 'Tactical Search & Engineering Suite',
    eyebrow: '[SERVICES // PROTOCOL_SUITE]',
    descLine1: 'Full-stack algorithmic SEO, Generative Engine Optimization (GEO),',
    descLine2: 'conversion-driven Google Ads campaigns, and sub-2s web speed.',
    tag1: 'Core Search Ops',
    tag1Sub: 'Technical & On-Page SEO',
    tag2: 'AI / GEO Engine',
    tag2Sub: 'LLM Citations & Perplexity',
    tag3: 'Performance Ads',
    tag3Sub: 'Google Ads & CRO',
  },
  {
    base: 'public/og/seo-service-hero',
    title: 'Core Search Capabilities & Defense',
    eyebrow: '[SEO // CORE_SEARCH_SYSTEMS]',
    descLine1: 'Full-stack algorithmic ranking defense and semantic knowledge engineering.',
    descLine2: 'Deterministic crawl prioritization and Core Web Vitals acceleration.',
    tag1: 'Algorithmic Defense',
    tag1Sub: 'Penalty protection & crawl optimization',
    tag2: 'Semantic Graph',
    tag2Sub: 'Entity knowledge architecture',
    tag3: 'CWV Acceleration',
    tag3Sub: 'Sub-2s page speed target',
  },
  {
    base: 'public/og/technical-onpage-hero',
    title: 'Technical & On-Page SEO Infrastructure',
    eyebrow: '[SEO // TECHNICAL_ONPAGE]',
    descLine1: 'Defect elimination, sub-second Core Web Vitals optimization,',
    descLine2: 'and deterministic internal link graphs for search crawlers.',
    tag1: 'Crawl Precision',
    tag1Sub: 'Zero orphan crawl budget waste',
    tag2: 'CWV Performance',
    tag2Sub: 'Sub-1.2s LCP and INP defense',
    tag3: 'Structured Data',
    tag3Sub: 'Rich schema entity validation',
  },
  {
    base: 'public/og/content-authority-hero',
    title: 'Content Authority & Topical Clustering',
    eyebrow: '[SEO // CONTENT_AUTHORITY]',
    descLine1: 'Engineered topical authority hubs, semantic entity association,',
    descLine2: 'and high-ranking search content architecture.',
    tag1: 'Topical Hubs',
    tag1Sub: 'Exhaustive thematic coverage',
    tag2: 'Entity Mapping',
    tag2Sub: 'Knowledge base synchronization',
    tag3: 'Authority Audits',
    tag3Sub: 'Competitive content gap defense',
  },
  {
    base: 'public/og/local-seo-hero',
    title: 'Local SEO & Google Maps Dominance',
    eyebrow: '[SEO // LOCAL_SEARCH]',
    descLine1: 'Hyper-local geo-optimization, Google Maps listing dominance,',
    descLine2: 'and citation syndication for brick-and-mortar revenue growth.',
    tag1: 'Google Maps #1',
    tag1Sub: 'Top 3 local pack positioning',
    tag2: 'Local Citations',
    tag2Sub: 'NAP syndication across directories',
    tag3: 'Review Engine',
    tag3Sub: 'Reputation & customer velocity',
  },
  {
    base: 'public/og/services-web',
    title: 'Web Engineering & Performance Suite',
    eyebrow: '[WEB // ARCHITECTURE_SUITE]',
    descLine1: 'Astro 7 & Cloudflare Workers edge web engineering designed for',
    descLine2: 'sub-second load speeds, modern ergonomics, and conversion power.',
    tag1: 'Edge Native',
    tag1Sub: 'Cloudflare global network runtime',
    tag2: 'Zero Bloat',
    tag2Sub: 'Pure Tailwind & TypeScript stack',
    tag3: 'Conversion First',
    tag3Sub: 'Built for instant user conversion',
  },
  {
    base: 'public/og/web-design-hero',
    title: 'SEO-Driven Web Design & Speed',
    eyebrow: '[WEB // SEO_DESIGN]',
    descLine1: 'SEO-optimized web architecture built from the first line of code.',
    descLine2: 'Perfect Lighthouse 100 benchmarks and responsive mobile-first UX.',
    tag1: 'SEO Architected',
    tag1Sub: 'Crawl-ready hierarchy & schema',
    tag2: 'Lighthouse 100',
    tag2Sub: 'Core Web Vitals green across all devices',
    tag3: 'Mobile Ergonomics',
    tag3Sub: 'Tested across 15+ screen sizes',
  },
  {
    base: 'public/og/website-speed-hero',
    title: 'Website Speed & Core Web Vitals',
    eyebrow: '[WEB // CWV_OPTIMIZATION]',
    descLine1: 'Sub-2-second load times, sub-100ms INP responsiveness,',
    descLine2: 'and edge-cached asset pipelines for maximum search ranking boost.',
    tag1: 'Sub-2s LCP',
    tag1Sub: 'Lightning-fast asset rendering',
    tag2: 'Zero CLS',
    tag2Sub: 'Zero cumulative layout shifts',
    tag3: 'Edge Asset Cache',
    tag3Sub: 'Global 1-year immutable caching',
  },
  {
    base: 'public/og/ux-architecture-hero',
    title: 'UX Design & Information Architecture',
    eyebrow: '[WEB // UX_ARCHITECTURE]',
    descLine1: 'Conversion rate optimization, friction-free user flows,',
    descLine2: 'and cognitive ergonomics engineered for enterprise web platforms.',
    tag1: 'Friction Removal',
    tag1Sub: 'Zero drop-off user funnels',
    tag2: 'Data Telemetry',
    tag2Sub: 'Heatmaps & behavioral analysis',
    tag3: 'Design System',
    tag3Sub: 'Consistent brutalist tokens',
  },
  {
    base: 'public/og/landing-page-hero',
    title: 'High-Converting Landing Page Design',
    eyebrow: '[WEB // LANDING_PAGES]',
    descLine1: 'Custom landing pages engineered for paid Google Ads and social campaigns,',
    descLine2: 'A/B conversion rate optimization, and maximum lead capture.',
    tag1: 'CRO Optimized',
    tag1Sub: 'Built for paid acquisition ROI',
    tag2: 'Sub-Second Edge',
    tag2Sub: 'Zero bounce from slow page speed',
    tag3: 'Conversion API',
    tag3Sub: 'Direct server-side event tracking',
  },
  {
    base: 'public/og/services-marketing',
    title: 'Digital Marketing & Growth Engine',
    eyebrow: '[MARKETING // GROWTH_ENGINE]',
    descLine1: 'Integrated digital marketing, high-ROI Google Ads campaigns,',
    descLine2: 'and behavioral conversion funnels backed by verified analytics.',
    tag1: 'Paid Search',
    tag1Sub: 'High-intent acquisition campaigns',
    tag2: 'Retention Loops',
    tag2Sub: 'Automated lifecycle messaging',
    tag3: 'Attribution',
    tag3Sub: 'Deterministic multichannel tracking',
  },
  {
    base: 'public/og/marketing-engagement-hero',
    title: 'Digital Marketing Operations & Growth',
    eyebrow: '[MARKETING // ENGAGEMENT]',
    descLine1: 'Data-driven marketing operations, paid media optimization,',
    descLine2: 'and strategic lead funnels designed to scale revenue efficiently.',
    tag1: 'Paid Strategy',
    tag1Sub: 'Disciplined budget allocation',
    tag2: 'Engagement Loops',
    tag2Sub: 'Omnichannel user touchpoints',
    tag3: 'Verified LTV',
    tag3Sub: 'Measurable ROI on every dollar',
  },
  {
    base: 'public/og/marketing-google-ads-hero',
    title: 'Google Ads & PPC Advertising',
    eyebrow: '[MARKETING // GOOGLE_ADS]',
    descLine1: 'Targeted Google Search, Performance Max, and Shopping campaigns',
    descLine2: 'optimized for low CPA and maximum qualified customer acquisition.',
    tag1: 'Intent Targeting',
    tag1Sub: 'Capture ready-to-buy searchers',
    tag2: 'Negative Lists',
    tag2Sub: 'Zero wasted click spend',
    tag3: 'Budget Discipline',
    tag3Sub: 'Weekly ROAS & margin auditing',
  },
  {
    base: 'public/og/google-ads-hero',
    title: 'Google Ads & PPC Strategy',
    eyebrow: '[MARKETING // GOOGLE_ADS_PPC]',
    descLine1: 'Advanced Google Ads optimization: bid strategy, quality score recovery,',
    descLine2: 'and conversion tracking architecture for enterprise brands.',
    tag1: 'Quality Score',
    tag1Sub: 'Lower CPC with higher relevance',
    tag2: 'PMax Mastery',
    tag2Sub: 'Asset groups tailored by intent',
    tag3: 'Server Tracking',
    tag3Sub: '100% conversion visibility',
  },
  {
    base: 'public/og/integrated-campaigns-hero',
    title: 'Integrated Multi-Channel Ad Campaigns',
    eyebrow: '[MARKETING // INTEGRATED_ADS]',
    descLine1: 'Cross-channel ad campaigns synchronizing Google Search, LinkedIn,',
    descLine2: 'and social retargeting to accelerate customer acquisition.',
    tag1: 'Cross-Platform',
    tag1Sub: 'Search, Social & Retargeting sync',
    tag2: 'Audience Pooling',
    tag2Sub: 'First-party data remarketing',
    tag3: 'Full Funnel',
    tag3Sub: 'Awareness through closed sale',
  },
  {
    base: 'public/og/sales-funnel-hero',
    title: 'Sales Funnel Management & CRO',
    eyebrow: '[MARKETING // SALES_FUNNELS]',
    descLine1: 'Scientific funnel optimization, checkout friction reduction,',
    descLine2: 'and automated behavioral triggers to maximize customer lifetime value.',
    tag1: 'Friction Audit',
    tag1Sub: 'Eliminate drop-off touchpoints',
    tag2: 'A/B Split Tests',
    tag2Sub: 'Statistically verified page lifts',
    tag3: 'CRM Pipeline',
    tag3Sub: 'Real-time sales notification sync',
  },
  {
    base: 'public/og/social-media-hero',
    title: 'Social Media Strategy & Operations',
    eyebrow: '[MARKETING // SOCIAL_STRATEGY]',
    descLine1: 'High-authority social channel operations, B2B audience growth,',
    descLine2: 'and multi-channel distribution for enterprise technology brands.',
    tag1: 'B2B Authority',
    tag1Sub: 'LinkedIn & X thought leadership',
    tag2: 'Content Distribution',
    tag2Sub: 'Syndicated content pipelines',
    tag3: 'Audience Metrics',
    tag3Sub: 'Verified organic reach growth',
  },
  {
    base: 'public/og/social-media-content-hero',
    title: 'Social Media Content Production',
    eyebrow: '[MARKETING // SOCIAL_CONTENT]',
    descLine1: 'Engaging, brand-aligned visual and written social content designed',
    descLine2: 'to build organic credibility and direct buyer engagement.',
    tag1: 'Creative Design',
    tag1Sub: 'Neo-brutalist visual templates',
    tag2: 'Copywriting',
    tag2Sub: 'High-hook technical prose',
    tag3: 'Cadence Engine',
    tag3Sub: 'Consistent daily publishing',
  },
  {
    base: 'public/og/email-marketing-hero',
    title: 'Email Marketing & Retention Automation',
    eyebrow: '[MARKETING // EMAIL_RETENTION]',
    descLine1: 'Behavioral segmentation, automated lifecycle flows, and technical',
    descLine2: 'deliverability engineering for maximum subscriber lifetime value.',
    tag1: 'Deliverability',
    tag1Sub: 'SPF, DKIM & DMARC inbox defense',
    tag2: 'Trigger Flows',
    tag2Sub: 'Behavioral automated sequences',
    tag3: 'Subscriber LTV',
    tag3Sub: 'High open & click engagement',
  },
  {
    base: 'public/og/services-content',
    title: 'Content Engineering & Authority Hub',
    eyebrow: '[CONTENT // ENGINEERING_SUITE]',
    descLine1: 'Data-driven content architecture, semantic research, and technical',
    descLine2: 'publishing designed to rank on Google and power AI citations.',
    tag1: 'Semantic Depth',
    tag1Sub: 'Complete topical coverage',
    tag2: 'E-E-A-T Rigor',
    tag2Sub: 'Subject-matter verified copy',
    tag3: 'AI Citations',
    tag3Sub: 'Formatted for LLM answer retrieval',
  },
  {
    base: 'public/og/content-creation-hero',
    title: 'Technical Content Creation Services',
    eyebrow: '[CONTENT // PRODUCTION]',
    descLine1: 'Deep research, expert technical writing, and SEO-engineered articles',
    descLine2: 'that build trust with decision makers and search engine algorithms.',
    tag1: 'Expert Writing',
    tag1Sub: 'Written for engineering decision makers',
    tag2: 'Search Optimized',
    tag2Sub: 'Targeted keyword intent alignment',
    tag3: 'Editorial QA',
    tag3Sub: 'Strict review and fact verification',
  },
  {
    base: 'public/og/translation-hero',
    title: 'Technical SEO Translation & Hreflang',
    eyebrow: '[CONTENT // LOCALIZATION]',
    descLine1: 'Multi-lingual keyword adaptation, Hreflang architecture, and culturally',
    descLine2: 'nuanced technical translation for international market expansion.',
    tag1: 'Hreflang Tags',
    tag1Sub: 'Zero cross-region index conflicts',
    tag2: 'Intent Adaptation',
    tag2Sub: 'Local search queries and volume',
    tag3: 'Global Rankings',
    tag3Sub: 'Rank across worldwide Google regions',
  },
  {
    base: 'public/og/visual-content-hero',
    title: 'Visual Content & Technical Schematics',
    eyebrow: '[CONTENT // VISUAL_MEDIA]',
    descLine1: 'Custom technical diagrams, infographics, and visual assets',
    descLine2: 'designed to capture backlinks and simplify complex concepts.',
    tag1: 'Backlink Earning',
    tag1Sub: 'High-citation visual schematics',
    tag2: 'Data Visualization',
    tag2Sub: 'Clear technical communication',
    tag3: 'Brand Assets',
    tag3Sub: 'Vector-perfect brutalist styling',
  },
  {
    base: 'public/og/content-calendar-hero',
    title: 'Content Calendar & Publishing Strategy',
    eyebrow: '[CONTENT // CALENDAR_STRATEGY]',
    descLine1: 'Predictable, data-backed editorial calendars aligned with seasonal search',
    descLine2: 'demand and product release milestones.',
    tag1: 'Publishing Cadence',
    tag1Sub: 'Zero production delays',
    tag2: 'Trend Capture',
    tag2Sub: 'Seasonal keyword volume timing',
    tag3: 'Resource Plan',
    tag3Sub: 'Clear contributor accountability',
  },
  {
    base: 'public/og/ai-service-hero',
    title: 'Neural AI & Generative Engine Suite',
    eyebrow: '[AI // NEURAL_SUITE]',
    descLine1: 'Generative Engine Optimization (GEO/AEO), knowledge graph engineering,',
    descLine2: 'and LLM citation dominance across Perplexity, ChatGPT & Gemini.',
    tag1: 'AEO / GEO Dominance',
    tag1Sub: 'Featured in AI summary responses',
    tag2: 'Knowledge Entities',
    tag2Sub: 'Structured semantic data graphs',
    tag3: 'Agent Automation',
    tag3Sub: 'n8n & MCP AI agent integration',
  },
  {
    base: 'public/og/ai-content-hero',
    title: 'AI Content Automation & Verification',
    eyebrow: '[AI // CONTENT_AUTOMATION]',
    descLine1: 'Scalable programmatic content pipelines with deterministic fact checking,',
    descLine2: 'human-in-the-loop validation, and anti-hallucination guardrails.',
    tag1: 'Programmatic Scale',
    tag1Sub: 'Deterministic data pipelines',
    tag2: 'Anti-Hallucination',
    tag2Sub: 'Automated fact-checking audits',
    tag3: 'Human Polish',
    tag3Sub: 'Senior editorial review standards',
  },
  {
    base: 'public/og/analysis-strategy-hero',
    title: 'AI Strategy & Competitor Analysis',
    eyebrow: '[AI // STRATEGY_INTELLIGENCE]',
    descLine1: 'Algorithmic competitor footprint auditing, search intent modeling,',
    descLine2: 'and prioritized growth roadmaps for enterprise market leaders.',
    tag1: 'Competitor Footprint',
    tag1Sub: 'Reverse-engineer ranking signals',
    tag2: 'Intent Architecture',
    tag2Sub: 'Cluster high-value search queries',
    tag3: 'Action Backlog',
    tag3Sub: 'Prioritized ROI implementation steps',
  },

  // ==========================================
  // 3. BLOG POSTS & HUB
  // ==========================================
  {
    base: 'public/og/blog-hero',
    title: 'Engineering Dispatches & Search Insights',
    eyebrow: '[BLOG // TECHNICAL_DISPATCHES]',
    descLine1: 'Deep technical analysis on algorithmic SEO, Generative Engine Optimization,',
    descLine2: 'Google Ads budget economics, and edge web engineering.',
    tag1: 'Algorithmic SEO',
    tag1Sub: 'Mathematical ranking analysis',
    tag2: 'GEO / AEO Tactics',
    tag2Sub: 'LLM citation benchmarks',
    tag3: 'Web Architecture',
    tag3Sub: 'Astro 7 & Workers edge guides',
  },
  {
    base: 'public/og/geo-ai-citations-hero',
    title: 'GEO: How to Get Cited by Perplexity & ChatGPT',
    eyebrow: '[BLOG // GENERATIVE_ENGINE_OPT]',
    descLine1: 'Practical guide to entity clarity, JSON-LD schema, and technical citation',
    descLine2: 'triggers that win source citations in AI answer engines.',
    tag1: 'Entity Clarity',
    tag1Sub: 'Explicit semantic entity naming',
    tag2: 'Structured Citations',
    tag2Sub: 'Claim & evidence formatting',
    tag3: 'RAG Retrieval',
    tag3Sub: 'Optimized for LLM vector search',
  },
  {
    base: 'public/og/seo-tips-hero',
    title: 'Advanced SEO & Digital Marketing Strategy',
    eyebrow: '[BLOG // SEARCH_TACTICS]',
    descLine1: 'High-leverage organic search tactics, technical crawl optimization,',
    descLine2: 'and marketing automation strategies that produce compounding traffic.',
    tag1: 'Crawl Budget',
    tag1Sub: 'Direct spiders to money pages',
    tag2: 'Conversion Lifts',
    tag2Sub: 'Turn organic visits into revenue',
    tag3: 'Competitive Defense',
    tag3Sub: 'Protect high-value keyword positions',
  },
  {
    base: 'public/og/seo-web-design-hero',
    title: 'SEO-Friendly Web Design: The Technical Blueprint',
    eyebrow: '[BLOG // WEB_ENGINEERING]',
    descLine1: 'Architectural guide to combining speed, modern aesthetics, and Google-first',
    descLine2: 'structure from the very first line of code.',
    tag1: 'Clean Semantics',
    tag1Sub: 'Semantic HTML5 & clean hierarchy',
    tag2: 'Sub-2s Speeds',
    tag2Sub: 'Zero rendering blocking scripts',
    tag3: 'Responsive UX',
    tag3Sub: 'Mobile-first Google compliance',
  },
  {
    base: 'public/og/content-calendar-post-template',
    title: 'How to Build a High-ROI Content Calendar',
    eyebrow: '[BLOG // CONTENT_STRATEGY]',
    descLine1: 'Cadence planning, keyword prioritization, and scalable publishing workflows',
    descLine2: 'that align editorial schedules with search volume opportunities.',
    tag1: 'Keyword Mapping',
    tag1Sub: 'Prioritize by business intent',
    tag2: 'Cadence Rigor',
    tag2Sub: 'Weekly predictable production',
    tag3: 'Content Reuse',
    tag3Sub: 'Syndicate across multiple channels',
  },
  {
    base: 'public/og/content-authority-post-checklist',
    title: 'What is Page Authority & How to Grow It',
    eyebrow: '[BLOG // AUTHORITY_GROWTH]',
    descLine1: 'The definitive breakdown of page authority signals, internal linking topology,',
    descLine2: 'and the complete technical audit checklist for high Google rankings.',
    tag1: 'Link Equity',
    tag1Sub: 'Deterministic internal distribution',
    tag2: 'Anchor Precision',
    tag2Sub: 'Contextual keyword anchors',
    tag3: 'Audit Checklist',
    tag3Sub: 'Step-by-step authority evaluation',
  },

  // ==========================================
  // 4. PORTFOLIO CASE STUDIES & HUB
  // ==========================================
  {
    base: 'public/og/portfolio-hero',
    title: 'Enterprise Portfolio & Architecture Archive',
    eyebrow: '[PORTFOLIO // CASE_STUDIES]',
    descLine1: 'Verified search infrastructure results, agentic MCP platforms,',
    descLine2: 'and scale records achieved across global enterprise client operations.',
    tag1: 'Verified Telemetry',
    tag1Sub: 'Real Search Console proof',
    tag2: 'Edge Native',
    tag2Sub: 'Cloudflare Workers architecture',
    tag3: 'Enterprise Scale',
    tag3Sub: 'Millions of organic impressions',
  },
  {
    base: 'public/og/portfolio-asreseo-command-center',
    title: 'Asre SEO Command Center & MCP Gateway',
    eyebrow: '[PORTFOLIO // PROJECT_01_AI_MCP]',
    descLine1: 'Unified SEO Intelligence Platform & 32 Model Context Protocol tools',
    descLine2: 'connecting Google APIs, D1 database caching, and AI agents at the edge.',
    tag1: '32 MCP Tools',
    tag1Sub: 'Unified agent search interface',
    tag2: 'Cloudflare Edge',
    tag2Sub: 'Sub-50ms global API latency',
    tag3: 'D1 Warehousing',
    tag3Sub: 'Continuous automated GSC snapshots',
  },
  {
    base: 'public/og/portfolio-emdash-seo',
    title: 'WebABC SEO Suite (emdash-seo)',
    eyebrow: '[PORTFOLIO // PROJECT_02_EDGE_CMS]',
    descLine1: 'Edge-native programmatic CMS & audit engine on Astro 7 and TypeScript,',
    descLine2: 'scaling automated site health checks with sub-2s page speed.',
    tag1: 'Astro 7 Core',
    tag1Sub: 'Zero runtime JS overhead',
    tag2: 'Automated Audits',
    tag2Sub: 'Deterministic technical crawls',
    tag3: '100% Verified',
    tag3Sub: 'Passed all deployment benchmarks',
  },
  {
    base: 'public/og/portfolio-fintech-scaleup',
    title: 'Fintech Scaleup Search Dominance',
    eyebrow: '[PORTFOLIO // PROJECT_03_FINTECH]',
    descLine1: 'Zero index decay, sub-second LCP speed, and +312% organic volume lift',
    descLine2: 'in a high-compliance, hyper-competitive financial search ecosystem.',
    tag1: '+312% Organic',
    tag1Sub: 'Compounding non-brand traffic',
    tag2: 'CWV 100/100',
    tag2Sub: 'Perfect performance score',
    tag3: 'Zero Penalty',
    tag3Sub: '100% white-hat algorithmic safety',
  },
  {
    base: 'public/og/portfolio-b2b-saas-global',
    title: 'Global B2B SaaS Enterprise Visibility',
    eyebrow: '[PORTFOLIO // PROJECT_04_SAAS]',
    descLine1: 'Multi-region Hreflang architecture, tier-1 international rankings,',
    descLine2: 'and high-converting buyer intent capture across 12 countries.',
    tag1: 'Global Reach',
    tag1Sub: '12-region localized search',
    tag2: 'Tier-1 Rankings',
    tag2Sub: 'Dominating high-ACV keywords',
    tag3: 'Hreflang Sync',
    tag3Sub: 'Zero cross-country cannibalization',
  },
  {
    base: 'public/og/portfolio-global-ecommerce-rescue',
    title: 'Global E-Commerce Migration & Recovery',
    eyebrow: '[PORTFOLIO // PROJECT_05_ECOM]',
    descLine1: 'Zero-traffic-loss re-platforming, crawl budget recovery,',
    descLine2: 'and +184% organic revenue expansion across 50,000+ SKU catalog.',
    tag1: 'Zero Loss',
    tag1Sub: 'Flawless 301 redirect mapping',
    tag2: '+184% Revenue',
    tag2Sub: 'High-intent product ranking',
    tag3: 'Crawl Defense',
    tag3Sub: 'Eliminated faceted URL bloat',
  },
];

async function main() {
  console.log(`Starting generation for ${allCards.length} OpenGraph cards (PNG + JPG)...`);
  let successCount = 0;

  for (const card of allCards) {
    try {
      const svg = buildOgSvg(card);
      await renderCardPair(svg, path.resolve(card.base));
      successCount++;
    } catch (err) {
      console.error(`Failed generating ${card.base}:`, err);
    }
  }

  console.log(`Completed ${successCount}/${allCards.length} cards successfully.`);
}

main().catch(console.error);
